settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: globalNotes
  path: /Users/ygzheng/Documents/playground/goTest/src/xslate/cmd/globalNotes
  commands:
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
