settings:
  legacy:
    force: false
    interval: 100ms
server:
  status: false
  open: false
  host: localhost
  port: 5001
schema:
- name: xslate
  path: .
  commands:
    run:
      status: ture
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
